### ISSUE TITLE
关于授权协议

### ISSUE THREAD

**Issue by cloudwebrtc** [alberliu/fim#1]
大侠，请问此项目准备用什么授权协议，准备抄作业，xD, 
另外，我写了flutter-webrtc 插件，可以用来实现视频通话/视频会议。

**Comment by alberliu** [comment]
没有授权协议，随便用

**Comment by alberliu** [comment]
另外，我写了flutter-webrtc 插件，可以用来实现视频通话/视频会议。
关于这个可以啊，有兴趣的话，我们一块集成到里面

**Comment by cloudwebrtc** [comment]
@alberliu 阔以阔以，周末我研究一下fim工作流程，看如何即成webrtc 信令，应该不难。
