### ISSUE TITLE
我在哪里输入服务端的地址和端口呢？

### ISSUE THREAD

**Issue by v-dao** [alberliu/fim#2]
如题。

**Comment by v-dao** [comment]
我在releases的apk中没有找到，设置服务端信息的页面。

**Comment by alberliu** [comment]
这个需要该代码，你搜一下这两行代码
const String baseUrl = "111.229.238.28";
const String uploadUrl = "http://111.229.238.28:8085/upload";

**Comment by v-dao** [comment]
行吧，我还得安装android sdk和flutter。能不能发布一个debug版本，可以在软件中设置服务端的信息，可以让像我这样寻找im解决方案的人，可以尽快的用起来。谢谢大佬的回答。
